### ISSUE TITLE
If the user does not have their docket number should we allow them to continue the interview?

### ISSUE THREAD

**Issue by KarlaRFuentes** [SuffolkLITLab/docassemble-MATCTaxLienAnswer#37]
The current Guide and File asks for the docket number in the first question and makes it required to give one but the user can put anything and it will allow them to continue. In our interview we allow the user to click an option that says they don't have it and are allowed to continue. If the user does not have their docket number should we just kick them out of the interview?

**Comment by beilert00** [comment]
ANSWER FROM CT LEADERSHIP: 

Usually, people type the number in and it verifies. Joe says to allow people to use it, even if it means skipping.

Maybe we can do the shaded format for the numbers to guide users, an example was given where a page has a social security # format so the users knew which numbers to look for on their documents and what order the number would be in. Consider sticking with "docket number" instead of "case number."

https://www.mass.gov/info-details/how-to-search-court-dockets#video-introduction:-how-to-search-court-dockets-
^ For if you don’t know how to access your number. Maybe we can link this.

**Comment by KarlaRFuentes** [comment]
Decision-makers would like us to add a note telling the user they can find the docket number on the citation or complaint. The note with the example of the number should also have a disclaimer that it is case and number sensitive.

**Comment by samglover** [comment]
Related question: it looks like the court uses "docket number" and "case number" interchangeably. We should include a note about that on the page where we ask for it.

**Comment by KarlaRFuentes** [comment]
Docket number page has been reworked in the following ways:
- The "I don't know the number" option was taken away 
- The field label was changed from "case number" to "docket number" to match how the number is referenced on the pdf form and the tax lien complaint and citation. 
- I made the field Mandatory: False.  Court leadership has not come to a clear decision on whether they want the interview to require the information to be given before the user can proceed, as accessibility is a concern (I will create an issue to discuss if there is a definite decision during the next check in meeting with the decision makers). 
- I also created a note under the question that includes:
       - An example of the format of a docket number 
       - I also let the user know they can find this number in the tax lien complaint and citation 
       - I also let the user know that the phrases "case number" and "docket number" as interchangeable in case they encounter either. 
       - I also linked a video that shows the user how to find their docket number online through mass.gov.
